<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Male</name>
   <tag></tag>
   <elementGuidId>3bb2bf37-ec47-4a8a-a3bb-dd0c008b244d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='q26']//child::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='q26']//child::label[1]</value>
      <webElementGuid>c659bc0d-7706-43ea-b589-8a9e65f2b90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Volunter Sign Up/iframe_Form</value>
      <webElementGuid>2192515d-7050-4627-8d10-e39704211186</webElementGuid>
   </webElementProperties>
</WebElementEntity>
